[package]
name = "fractal-backend"
version = "0.1.0"
authors = ["Daniel García Moreno <danigm@wadobo.com>"]

[dependencies]
rusqlite = "0.16.0"
failure = "0.1.3"
lazy_static = "1.2.0"
serde_json = "1.0.33"
chrono = "0.4.6"

[dependencies.fractal-matrix-api]
path = "../fractal-matrix-api"
