[package]
name = "fractal-backend"
version = "0.1.0"
authors = ["Daniel García Moreno <danigm@wadobo.com>"]

[dependencies]
rusqlite = "0.15.0"
failure = "0.1.3"
lazy_static = "1.2.0"

[dependencies.fractal-matrix-api]
path = "../fractal-matrix-api"
