stages:
  - test

flatpak:
    image: registry.gitlab.com/alatiera/gnome-nightly-oci/rust-bundle:latest
    stage: test
    script:
        # Build the flatpak deps
        - flatpak-builder --stop-at=fractal app flatpak/org.gnome.Fractal.json

        # https://gitlab.gnome.org/alatiera/Hammond/issues/55
        # Force regeneration of gresources regardless of artifacts chage
        - flatpak-builder --run app flatpak/org.gnome.Fractal.json glib-compile-resources --sourcedir=fractal-gtk/res/ fractal-gtk/res/resources.xml

        - flatpak-builder --run app flatpak/org.gnome.Fractal.json meson --prefix=/app --libdir=/app/lib _build
        - flatpak-builder --run app flatpak/org.gnome.Fractal.json ninja -C _build install
        - flatpak-builder --finish-only app flatpak/org.gnome.Fractal.json
        - flatpak build-export repo app

        # Create a flatpak bundle for designers to use
        - flatpak build-bundle repo fractal-dev.flatpak org.gnome.Fractal
        # Run the tests
        - flatpak-builder --run app flatpak/org.gnome.Fractal.json cargo test

    artifacts:
        paths:
            - fractal-dev.flatpak
        expire_in: 2 days

    cache:
        # JOB_NAME - Each job will have it's own cache
        # ^ Keep diffrerent caches for each branch
        key: "$CI_JOB_NAME"
        paths:
          - .flatpak-builder/cache/
          - target/

pages:
    stage: deploy
    only:
        - master
    script:
        - cargo doc --no-deps -p fractal-api
        - cargo rustdoc -p fractal-gtk -- --document-private-items
        - rm -rf public
        - mv target/doc/ public
    artifacts:
        paths:
          - public
