[package]
authors = ["Daniel Garcia <danigm@wadobo.com>"]
name = "fractal-matrix-api"
version = "3.29.6"
workspace = "../"

description = """
Library to communicate with a Matrix.org server
"""
keywords = [
    "matrix", "fractal"
]
license = "GPL-3.0"
repository = "https://gitlab.gnome.org/World/fractal"
documentation = "https://world.pages.gitlab.gnome.org/fractal/fractal_matrix_api/index.html"

[dependencies]
glib = "0.5.0"
mime = "0.3.8"
regex = "1.0.2"
reqwest = "0.8.6"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
time = "0.1.40"
tree_magic = "0.2.0"
url = "1.7.1"
urlencoding = "1.0.0"
md5 = "0.3.7"

[dependencies.cairo-rs]
features = ["png"]
version = "0.4.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4.4"
